baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'flatgraph'
theme = 'relearn'

[params]
  themeVariant = 'learn-customized'
  disableLandingPageButton = false
  landingPageName = 'Overview'
  showVisitedLinks = false
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard=true
  disableToc = false
  disableBreadcrumb = true
  disableNextPrev = true

[[menu.shortcuts]]
  name = "<i class='fa-fw fab fa-github'></i> GitHub repo"
  url = "https://github.com/joernio/flatgraph"
  weight = 10

[[menu.shortcuts]]
  name = "<img src='https://maven-badges.herokuapp.com/maven-central/io.joern/flatgraph-core_3/badge.svg' alt='latest release' />"
  url = "https://maven-badges.herokuapp.com/maven-central/io.joern/flatgraph-core_3"
  weight = 20
