baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'flatgraph'
theme = 'relearn'

[params]
  themeVariant = 'learn-customized'
  disableLandingPageButton = false
  landingPageName = 'Overview'
  showVisitedLinks = false
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard=true
  disableToc = false
  disableBreadcrumb = true
  disableNextPrev = true

[[menu.shortcuts]]
  name = "<i class='fa-fw fab fa-github'></i> git repository"
  url = "https://github.com/joernio/flatgraph"
  weight = 10

[[menu.shortcuts]]
  name = "<img src='https://img.shields.io/maven-central/v/io.joern/flatgraph-core_3' alt='latest release' />"
  url = "https://repo1.maven.org/maven2/io/joern/flatgraph-core_3/"
  weight = 20